language: php

sudo: false

php:
  - 7.2
  - 7.3

env:
  matrix:
    - LUMEN=^6.0

matrix:
  fast_finish: true
  allow_failures:
    - env: LUMEN=^6.0

before_install:
  - phpenv config-rm xdebug.ini || true

install:
  - travis_retry composer require "illuminate/contracts=${LUMEN}" --prefer-dist --no-interaction --no-suggest

test:
  - echo "Skipping test"

script: echo "Skipping test"

# script: vendor/bin/phpunit --verbose
